# Generated by Django 2.1.2 on 2018-11-08 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('agua', '0008_auto_20181108_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condominodocondominio',
            name='condominio',
        ),
        migrations.RemoveField(
            model_name='condominodocondominio',
            name='condomino',
        ),
        migrations.RemoveField(
            model_name='hidrometro',
            name='condominoDoCondominio',
        ),
        migrations.RemoveField(
            model_name='pagamentocondomino',
            name='condominoDoCondominio',
        ),
        migrations.DeleteModel(
            name='CondominoDoCondominio',
        ),
    ]
