# Generated by Django 2.1.2 on 2018-11-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('agua', '0010_auto_20181108_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicao',
            name='consumo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
