# Generated by Django 2.1.2 on 2018-11-08 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('agua', '0011_medicao_consumo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicao',
            options={'get_latest_by': 'cmpt__competencia'},
        ),
        migrations.AddField(
            model_name='competencia',
            name='condominio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agua.Condominio'),
            preserve_default=False,
        ),
    ]
