# Generated by Django 2.1.2 on 2018-10-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='nome_conhecido',
            field=models.CharField(max_length=51),
        ),
    ]
