# Generated by Django 2.1.2 on 2018-11-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0003_auto_20181108_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='data_fechamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagamentocondomino',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
