# Generated by Django 2.1.2 on 2018-11-08 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0004_auto_20181108_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='competencia',
        ),
    ]
