# Generated by Django 2.1.2 on 2018-11-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0005_remove_despesa_competencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicao',
            name='competencia',
        ),
        migrations.RemoveField(
            model_name='pagamentocondomino',
            name='competencia',
        ),
    ]
