# Generated by Django 2.1.2 on 2018-11-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0006_auto_20181108_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='condomino',
            name='condominio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='agua.Condominio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condomino',
            name='endereco_unidade',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='condomino',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
