# Generated by Django 2.1.2 on 2018-11-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0007_auto_20181108_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='hidrometro',
            name='condomino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='agua.Condomino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamentocondomino',
            name='condomino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agua.Condomino'),
        ),
    ]
