# Generated by Django 2.1.2 on 2018-11-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0009_auto_20181108_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencia',
            options={'get_latest_by': 'competencia'},
        ),
    ]
